In [1]:
import numpy as np

In [5]:
my_list =  [1, 2, 3, 4, 5]
my_array = np.array(my_list)

In [6]:
type(my_array)

numpy.ndarray

In [7]:
my_array

array([1, 2, 3, 4, 5])

In [8]:
my_array.shape

(5,)

In [9]:
my_list1 = [1, 2, 3, 4, 5]
my_list2 = [4, 5, 6, 7, 8]
my_list3 = [7, 8, 9, 10, 11]
my_array = np.array([my_list1, my_list2, my_list3])
my_array

array([[ 1,  2,  3,  4,  5],
       [ 4,  5,  6,  7,  8],
       [ 7,  8,  9, 10, 11]])

In [10]:
my_array.shape

(3, 5)

In [11]:
my_array.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  4],
       [ 5,  6,  7],
       [ 8,  7,  8],
       [ 9, 10, 11]])

In [ ]:
array_2= np.array([1,2,3,4,5,6,7,8,9,10,11,12])
array_2

In [2]:
list_1 = [1, 2, 3, 4, 5]
list_2 = [2, 3, 4, 5, 6]
list_3 = [9, 7, 6, 8, 9] 
array_3 = np.array([list_1,list_2,list_3])
array_3

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [4]:
array_3.shape

(3, 5)

In [ ]:
# In numpy [a,b] - a represents rows and b represents columns. 
# So, if we want to select 1st row and all columns then we will write [0,:] because 0 represents 1st row and : represents all columns. 
# If we want to select 2nd row and 1st column then we will write [1:2,0:1] because 1:2 represents 2nd row and 0:1 represents 1st column. 
# If we want to select 2nd and 3rd row and 1st column then we will write [1:3,0:1] because 1:3 represents 2nd and 3rd row and 0:1 represents 1st column.

In [6]:
array_3[0,:]

array([1, 2, 3, 4, 5])

In [8]:
array_3[1:2,0:1]

array([[2]])

In [10]:
array_3[1:3,0:1]

array([[2],
       [9]])

In [18]:
array_3[:,:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [28]:
array_3[0:2,0:2]

array([[1, 2],
       [2, 3]])

Explanation: here we are selecting 1st and 2nd row and 1st and 2nd column. 
So, we will write [0:2,0:2] because 0:2 represents 1st and 2nd row and 0:2 represents 1st and 2nd column.


In [4]:
array_3[1:2,2:3]

array([[4]])

In [3]:
array_3[1,2]

np.int64(4)